# Generated by Django 5.0.2 on 2024-03-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('gpa', models.FloatField(max_length=3)),
                ('courses', models.ManyToManyField(related_name='students', to='lab.course')),
            ],
        ),
    ]
